### ISSUE TITLE
BA-000.2 - Add and Update CONTRIBUTING.md to yna_backend

### ISSUE THREAD

**Issue by SincerelyBrittany** [Young-N-Ambitious/yna_backend#2]
Copy the [CONTRIBUTING.md](https://github.com/Young-N-Ambitious/yna_frontend/blob/main/CONTRIBUTING.md) from the yna_frontend and add it to the yna_backend. Make sure to update the docs so that where it says "yna-frontend", it should now say "yna_backend"

**Comment by najeebkp** [comment]
hi @SincerelyBrittany  please assign this task to me. I'll take care.

**Comment by Sydnee510** [comment]
> hi @SincerelyBrittany please assign this task to me. I'll take care.

Just assigned to you @najeebkp :)
