### ISSUE TITLE
BA-001 Enable CORS(Cross Origin Resource Sharing)

### ISSUE THREAD

**Issue by Sydnee510** [Young-N-Ambitious/yna_backend#5]
CORS allows others to access your API. To prevent unwanted access to your API, Rails automatically disables CORS. Let's enable CORS so others can get access our delicious data!
In the file explorer of your newly created Rails API, expand the following directories to open cors.rb file.
config>initializers>cors.rb

Allow all ('*') origins and resources 

Then once you update the cors.rb file, scroll down and open up the Gemfile and enable the "gem 'rack-cors' "

 Once you do these two things, run 'bundle install' and push up your changes.

**Comment by stef-codes** [comment]
@LuisCastilloKC Can you update this?
